### ISSUE TITLE
As a user, I want to scroll pages

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/bookmarklet#1]
## Overview
The first thing we'll need is the ability to scroll pages, both vertically and horizontally! We'll be testing this on Chrome, Firefox, and IE.

## Tasks
- [ ] Scroll pages vertically
- [ ] Scroll pages horizontally
- [ ] Adjust scroll speeds

## Test on
- [ ] https://en.wikipedia.org/wiki/Main_Page
- [ ] https://www.youtube.com/
- [ ] https://twitter.com
