### ISSUE TITLE
As a user, I need a control panel to adjust settings

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/bookmarklet#2]
## Overview
It can be a pain to constantly change variables to adjust settings, so let's use a [control-panel](https://github.com/freeman-lab/control-panel) to help us with adjust settings in real time.

## Tasks
- [ ] Add the control panel
- [ ] Add fields to adjust PoseNet settings
- [ ] Add fields to adjust sensitivities
